export enum RoleType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  CONTENT_EDITOR = 'CONTENT_EDITOR',
  RECRUITER = 'RECRUITER',
  AUDITOR = 'AUDITOR',
}

export enum ContentStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  TRASHED = 'TRASHED',
}

export enum PageLayoutType {
  DEFAULT = 'DEFAULT',
  FULL_WIDTH = 'FULL_WIDTH',
  LANDING = 'LANDING',
  MINIMAL = 'MINIMAL',
}

export enum ComponentType {
  HERO = 'HERO',
  FEATURE_GRID = 'FEATURE_GRID',
  METRICS_BANNER = 'METRICS_BANNER',
  CTA_STRIP = 'CTA_STRIP',
  LOGO_CLOUD = 'LOGO_CLOUD',
  TESTIMONIAL_SLIDER = 'TESTIMONIAL_SLIDER',
  ACCORDION_FAQ = 'ACCORDION_FAQ',
  TABBED_SOLUTIONS = 'TABBED_SOLUTIONS',
  CUSTOM_HTML = 'CUSTOM_HTML',
}

export enum MediaStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum InquiryStatus {
  NEW = 'NEW',
  QUALIFIED = 'QUALIFIED',
  ASSIGNED = 'ASSIGNED',
  CONTACTED = 'CONTACTED',
  OPPORTUNITY = 'OPPORTUNITY',
  DISQUALIFIED = 'DISQUALIFIED',
}

export enum ApplicationStatus {
  NEW = 'NEW',
  SCREENING = 'SCREENING',
  INTERVIEWING = 'INTERVIEWING',
  OFFER = 'OFFER',
  REJECTED = 'REJECTED',
  HIRED = 'HIRED',
}
